import { Product, Timing } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'marine-collagen',
    name: 'Marine Collagen + Vitamin C',
    subtitle: 'کلاژن دریایی + ویتامین C',
    description: 'این محصول برای سلامت پوست، مو و ناخن‌ها طراحی شده است. حاوی ۹۷.۵٪ کلاژن دریایی خالص و ۲.۵٪ ویتامین C است. کلاژن دریایی ۱.۵ برابر بهتر از منابع دیگر جذب می‌شود.',
    benefits: [
      'درخشندگی و شفافیت پوست',
      'کاهش چین و چروک',
      'تقویت مفاصل',
      'سلامت مو و ناخن'
    ],
    ingredients: ['کلاژن دریایی خالص (۹۷.۵٪)', 'ویتامین C (۲.۵٪)'],
    dosage: '۲ کپسول در روز پیش از صبحانه',
    timing: Timing.Morning,
    price: 7300000,
    duration: 'مناسب برای مصرف ۱ ماه',
    imageColor: 'bg-cyan-100',
    category: 'beauty',
    rating: 4.8,
    reviews: 124,
    stock: 15,
    expirationDate: '2025/12/01',
    points: 75
  },
  {
    id: 'omega-3',
    name: 'Omega 3',
    subtitle: 'روغن سالمون خالص',
    description: 'سلامت عمومی، ایمنی، عملکرد مغز و قلب را تقویت می‌کند. روغن سالمون گرید یک (۱۰۰٪ خالص).',
    benefits: [
      'سلامت قلب و عروق',
      'کاهش التهاب',
      'حمایت از عملکرد مغز و مفاصل',
      'تقویت سیستم ایمنی'
    ],
    ingredients: ['روغن سالمون خالص'],
    dosage: '۲ کپسول ژل نرم در روز همراه با غذا',
    timing: Timing.WithFood,
    price: 6300000,
    duration: 'مناسب برای مصرف ۱ ماه',
    imageColor: 'bg-orange-100',
    category: 'health',
    rating: 4.9,
    reviews: 89,
    stock: 42,
    expirationDate: '2026/03/15',
    points: 65
  },
  {
    id: 'd3-k2',
    name: 'Vitamin K2 + D3',
    subtitle: '+ زردچوبه',
    description: 'ترکیبی از ویتامین D3 و K2 همراه با زردچوبه ارگانیک برای جذب بهتر کلسیم و کاهش التهاب.',
    benefits: [
      'جذب کلسیم',
      'سلامت استخوان',
      'تقویت ایمنی',
      'ضد التهاب قوی'
    ],
    ingredients: ['ویتامین D3', 'ویتامین K2', 'زردچوبه ارگانیک'],
    dosage: '۱ کپسول در روز همراه با غذا',
    timing: Timing.WithFood,
    price: 4300000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-yellow-100',
    category: 'health',
    rating: 4.7,
    reviews: 56,
    stock: 8,
    expirationDate: '2025/11/20',
    points: 45
  },
  {
    id: 'recovery',
    name: 'Recovery',
    subtitle: 'ریکاوری',
    description: 'شبی راحت و روزی پرانرژی را فراهم می‌کند. ترکیبی از ویتامین‌های گروه B و منیزیم برای کاهش خستگی.',
    benefits: [
      'تقویت ایمنی',
      'کاهش خستگی',
      'حمایت از متابولیسم انرژی',
      'بهبود کیفیت خواب'
    ],
    ingredients: ['ویتامین B12', 'ویتامین B6', 'ویتامین C', 'منیزیم'],
    dosage: '۲ کپسول شب قبل از خواب',
    timing: Timing.Night,
    price: 4500000,
    duration: 'مناسب برای مصرف ۱ ماه',
    imageColor: 'bg-red-100',
    category: 'health',
    rating: 4.6,
    reviews: 42,
    stock: 25,
    expirationDate: '2025/10/05',
    points: 45
  },
  {
    id: 'weight-control',
    name: 'Weight',
    subtitle: 'کنترل وزن',
    description: 'ترکیبی قدرتمند برای کنترل وزن شامل پریرین (Berberine) و گلوکومانان که به تنظیم قند خون و اشتها کمک می‌کند.',
    benefits: [
      'کاهش اشتها',
      'کنترل وزن',
      'تنظیم قند خون',
      'افزایش متابولیسم'
    ],
    ingredients: ['بربرین (Berberine)', 'گلوکومانان', 'دارچین کاسیا', 'کروم'],
    dosage: '۱ کپسول ۳۰ دقیقه قبل از غذا',
    timing: Timing.BeforeMeal,
    price: 7400000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-green-100',
    category: 'health',
    rating: 4.5,
    reviews: 38,
    stock: 0,
    expirationDate: '2025/08/30',
    points: 75
  },
  {
    id: 'bright',
    name: 'Bright',
    subtitle: 'روشن‌کننده پوست',
    description: 'رنگ پوست را روشن کرده، تجمع رنگدانه‌ها و جای جوش را کاهش می‌دهد. حاوی آنتی‌اکسیدان‌های قوی.',
    benefits: [
      'روشن‌کنندگی پوست',
      'کاهش لک و جای جوش',
      'آنتی‌اکسیدان قوی',
      'یکدست‌کننده رنگ پوست'
    ],
    ingredients: ['گلوتاتیون', 'ویتامین C', 'ویتامین‌ها'],
    dosage: '۱ کپسول در روز',
    timing: Timing.WithFood,
    price: 7400000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-gray-100',
    category: 'beauty',
    rating: 4.8,
    reviews: 95,
    stock: 12,
    expirationDate: '2026/01/10',
    points: 75
  },
  {
    id: 'longevity',
    name: 'Longevity',
    subtitle: 'لانگیویتی',
    description: 'ضد پیری در سطح سلولی. ترکیب رسوراترول، عصاره زرشک و کوآنزیم Q10 برای سلامت قلب و عروق و طول عمر سالم.',
    benefits: [
      'انرژی سلولی',
      'محافظت از سلول‌ها',
      'سلامت قلب',
      'طول عمر سالم و تمرکز'
    ],
    ingredients: ['رزوراترول', 'عصاره زرشک (Berberry)', 'کوآنزیم Q10 (Coenzyme Q10)'],
    dosage: '۱ کپسول در روز همراه با غذا',
    timing: Timing.WithFood,
    price: 7400000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-purple-100',
    category: 'vitality',
    rating: 5.0,
    reviews: 21,
    stock: 5,
    expirationDate: '2026/05/22',
    points: 75
  },
  {
    id: 'probi-plus',
    name: 'Probi+',
    subtitle: 'پروبیوتیک پلاس',
    description: 'ترکیبی کامل برای سلامت روده. شامل ۱۸ سویه پروبیوتیک زنده، باکتری‌های غیرفعال و پری‌بیوتیک‌ها.',
    benefits: [
      'تنظیم فلور روده',
      'کاهش نفخ',
      'تقویت ایمنی',
      'سلامت پوست و خلق‌وشو'
    ],
    ingredients: ['۱۸ سویه پروبیوتیک زنده', 'FOS', 'XOS', 'اینولین', 'باکتری‌های غیرفعال'],
    dosage: '۱ کپسول قبل از صبحانه',
    timing: Timing.Morning,
    price: 7400000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-emerald-100',
    category: 'health',
    rating: 4.9,
    reviews: 110,
    stock: 60,
    expirationDate: '2025/09/14',
    points: 75
  },
  {
    id: 'nad-plus',
    name: 'NAD+',
    subtitle: 'ناد پلاس',
    description: 'افزایش انرژی و دفاع آنتی‌اکسیدانی. NAD+ به بازسازی سلولی و جوان‌سازی کمک می‌کند.',
    benefits: [
      'انرژی سلولی',
      'بازسازی سلولی',
      'تمرکز',
      'جوان‌سازی'
    ],
    ingredients: ['NAD+', 'عصاره بلوبری', 'دانه انگور', 'ویتامین B12'],
    dosage: '۱ کپسول قبل از صبحانه',
    timing: Timing.Morning,
    price: 8500000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-blue-100',
    category: 'vitality',
    rating: 4.7,
    reviews: 33,
    stock: 18,
    expirationDate: '2026/02/28',
    points: 85
  },
  {
    id: 'boost-her',
    name: 'Boost Her',
    subtitle: 'بوست هر (بانوان)',
    description: 'فرمول قوی و همه‌جانبه برای بانوان. تعادل هورمونی، انرژی، سلامت جنسی و باروری را تقویت می‌کند.',
    benefits: [
      'تعادل هورمونی',
      'افزایش انرژی',
      'بهبود باروری',
      'تقویت میل جنسی',
      'سلامت مجاری ادراری و ایمنی'
    ],
    ingredients: ['فولیک اسید', 'زینک', 'ویتامین B6', 'آهن بیس‌گلیسینات', 'ماکا', 'عصاره گن‌بری (Chasteberry)', 'موناسا پواما', 'مایو-اینوزیتول'],
    dosage: '۱ کپسول همراه صبحانه با یک لیوان آب',
    timing: Timing.Breakfast,
    price: 7400000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-pink-100',
    category: 'vitality',
    rating: 4.8,
    reviews: 67,
    stock: 30,
    expirationDate: '2025/12/12',
    points: 75
  },
  {
    id: 'boost-him',
    name: 'Boost Him',
    subtitle: 'بوست هیم (آقایان)',
    description: 'فرمول ویژه مردان برای تعادل سطح تستوسترون، انرژی، نشاط جنسی و تمرکز ذهنی.',
    benefits: [
      'افزایش تستوسترون',
      'انرژی و تمرکز',
      'عملکرد جنسی و باروری',
      'سلامت قلب و ایمنی'
    ],
    ingredients: ['ویتامین B3', 'شیلاجیت', 'جینسنگ', 'تریبولوس', 'ال-آرژنین', 'زینک سیترات', 'ویتامین‌ها'],
    dosage: '۱ کپسول همراه صبحانه با یک لیوان آب',
    timing: Timing.Breakfast,
    price: 7400000,
    duration: 'مناسب برای مصرف ۲ ماه',
    imageColor: 'bg-slate-200',
    category: 'vitality',
    rating: 4.8,
    reviews: 58,
    stock: 22,
    expirationDate: '2025/12/12',
    points: 75
  }
];